[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mlgf"
version = "0.0.1"
authors = [
  { name="Christian Venturella", email="christian.venturella@yale.edu" },
  { name="Christopher Hillenbrand" },
  { name="Jiachen Li" },
  { name="Tianyu Zhu" }
]
description = "Machine learning many-body Green's function and self-energy"
license = {'file'='LICENSE'}
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
]
[project.urls]
"Homepage" = "https://github.com/zhutianyu1991/mlgf"
"Bug Tracker" = "https://github.com/zhutianyu1991/mlgf/issues"

[tools.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
namespaces = true
where = ["./"]

[tool.black]
line-length = 120
target-version = ['py310']
include = '\.pyi?$'
skip-string-normalization = 1
# 'extend-exclude' excludes files or directories in addition to the defaults
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
(
  ^/foo.py    # exclude a file named foo.py in the root of the project
  | .*_pb2.py  # exclude autogenerated Protocol Buffer files anywhere in the project
)
'''

[tool.ruff]
line-length = 120
